version: '3.8'

services:
  app:
    image: openjdk:17
    container_name: task_management_system
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - .:/app
    working_dir: /app
    command: ./mvnw spring-boot:run